[[usage]]
== Usage

[NOTE]
====
Configuring your CAS server is beyond the scope of this document. There are many different approaches and this will most likely be done by IT staff. It's assumed here that you already have a running CAS server.
====

https://www.apereo.org/projects/cas[CAS] is a popular single sign-on implementation. It's open source and has an Apache-like license, and is easy to get started with but is also highly configurable. In addition it has clients written in Java, .Net, PHP, Perl, and other languages.

=== Installation

There isn't much that you need to do in your application to be a CAS client. Add a dependency in `build.gradle` for this plugin:

[source,java]
[subs="attributes"]
----
dependencies {
   ...
   compile 'org.grails.plugins:spring-security-cas:{project-version}'
   ...
----

then configure any required parameters and whatever optional parameters you want in application.yml or application.groovy. These are described in detail in the <<configuration>> section but typically you only need to set these properties:

[source,java]
----
grails:
   plugin:
      springsecurity:
         cas:
            loginUri: /login
            serviceUrl: http://localhost:8080/login/cas
            serverUrlPrefix: https://your-cas-server/cas
            proxyCallbackUrl: http://localhost:8080/secure/receptor
            proxyReceptorUrl: /secure/receptor
----

=== Single Signout

Single signout is enabled by default and enables signing out for all CAS-managed applications with one logout. This works best in the plugin when combined with the `afterLogoutUrl` parameter, for example:

[source,java]
----
grails:
   plugin:
      springsecurity:
         logout:
            afterLogoutUrl: https://your-cas-server/cas/logout?url=http://localhost:8080/
----

With this configuration, when a user logs out locally by navigating to `/logout/` they'll then be redirected to the CAS server's logout URL. This request includes a local URL to redirect back afterwards. When the whole process is finished they'll be logged out locally and at the CAS server, so subsequent secure URLs at the local server or other CAS-managed servers will require a new login.

If you don't want the single signout filter registered, you can disable the feature:

[source,java]
----
grails:
   plugin:
      springsecurity:
         cas:
            useSingleSignout: false
----

=== SAML Attribute Release

The CAS server can optionally release user attributes through http://jasig.github.io/cas/4.1.x/protocol/SAML-Protocol.html[SAML 1.1].  Instead of storing user details in the application's database, you can create a user record using these attributes. A user class (`grails.plugin.springsecurity.cas.userdetails.CasUser`) is included with the plugin.  To enable this feature:

[source,java]
----
grails:
   plugin:
      springsecurity:
         userLookup:
            userDomainClassName: grails.plugin.springsecurity.cas.CasUser
         cas:
            useSamlValidator: true
            driftTolerance: 1200
            authorityAttribute: roles
----

If you want to use SAML attributes with your own user class, add a class that implements the `grails.plugin.springsecurity.cas.userdetails.DomainUserMapper` interface and registering that as the `domainUserMapperService` bean in resources.groovy:

[source,java]
----
import com.mycompany.MyDomainUserMapperService

beans = {
   domainUserMapperService(MyDomainUserMapperService) {
      // any required properties
   }
}
----
